### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by alexalkis** [thorfdbg/rkrm-dos#1]
Thanks for the work.  I made a pass fixing typos.

Two non-exactly-typos
a) On the first table, I changed the second column to right aligned  to satisfy my OCD
b) AmigaOs -> AmigaOS, AmigaDos -> AmigaDOS

You can of course ignore the non-exactly-typos :)

[typos.patch](https://github.com/thorfdbg/rkrm-dos/files/12336458/typos.patch)

**Comment by thorfdbg** [comment]
Thanks, the patch has been applied by the time being, but a full spell-check run on the entire document is still to be done. I'm still working on issue reports.
