### ISSUE TITLE
notes "Rest"

### ISSUE THREAD

**Issue by No-Drei** [thorfdbg/rkrm-dos#18]
[RKRM DOS - Korrektur vom Rest.pdf](https://github.com/thorfdbg/rkrm-dos/files/15044477/RKRM.DOS.-.Korrektur.vom.Rest.pdf)

**Comment by kowoba** [comment]
Why don't you provide patches to the TeX instead of PDFs so one can see what changes you are making?

(I cannot even open those PDFs, they download as empty files... but maybe that's just me)

**Comment by thorfdbg** [comment]
Thanks a lot, also done with this one.
