### ISSUE TITLE
notes zu "Formatierungen" & "Path und File Names"

### ISSUE THREAD

**Issue by No-Drei** [thorfdbg/rkrm-dos#19]
[4.3_Paths_and_File_Names.pdf](https://github.com/thorfdbg/rkrm-dos/files/15067975/4.3_Paths_and_File_Names.pdf)
[RKRM DOS_Korrektur Formatierungen.pdf](https://github.com/thorfdbg/rkrm-dos/files/15067976/RKRM.DOS_Korrektur.Formatierungen.pdf)

**Comment by thorfdbg** [comment]
Reviewed the comments, thank you. Hopefully better now. These are really conversions (from numbers to strings), but I should have been clearer.
