### ISSUE TITLE
pdfLaTeX

### ISSUE THREAD

**Issue by norly** [thorfdbg/rkrm-dos#2]
Thank you so much for this work, I am looking forward to peeking under the hood of my nostalgia!

May I suggest using pdfLaTeX to generate the PDF, i.e. without the intermediary step via the DVI format? It outputs .pdf files natively, they are smaller, and they render much faster.

If there is a vector font package that you like (i.e. non-METAFONT package), that should again result in smaller files.

Again, thank you for your work for the Amiga community.

**Comment by thorfdbg** [comment]
Latest versions was redone with pdflatex and the times font, thus closing here. Thanks for the comment.
