### ISSUE TITLE
ACTION_WAIT_CHAR timeout units

### ISSUE THREAD

**Issue by cnvogelg** [thorfdbg/rkrm-dos#24]
Hi Thomas,

In the WaitForChar API call the timeout is specified correctly in microseconds.

But in the associated ACTION_WAIT_CHAR packet description (section 14.8.1 "Waiting for Input Becoming Available") the timeout in dp_Arg1 is described as being in ticks...  This seems to be wrong. My experiments showed that the timeout given there is in mircoseconds as well....

The units are confused in the example code in section 14.8.3 "Retrieving IORequest and Window Pointer from the Console" as well:

```
/*
** Maximum time to wait for the console
** to respond in ticks. May require              # <- correct: microseconds
** adjustment for slow connections.
*/
#define MAX_DELAY       200000

...

  if (WaitForChar(file,MAX_DELAY) == FALSE) {

```

Best,
Chris

**Comment by thorfdbg** [comment]
Thanks, I verified what the packet actually takes - it is microseconds indeed - and fixed it accordingly.
