### ISSUE TITLE
Minor corrections

### ISSUE THREAD

**Issue by mras0** [thorfdbg/rkrm-dos#3]
* 3.4 Indentation for the registers for Open() seems to be off by one
* 3.9.2 MEMF_CLEAR should probably be MEMF_PUBLIC in the description
* 5.1 "Under your feed" should be "Under your fee*t*"
* 5.3.4 FileParth should be FilePath

**Comment by thorfdbg** [comment]
Should hopefully be fixed now after the 4th iteration. Kindly check again.
