### ISSUE TITLE
Round of typo fixes

### ISSUE THREAD

**Issue by jman-schief** [thorfdbg/rkrm-dos#4]
As mentoned [in this comment on the EAB forum](https://eab.abime.net/showpost.php?p=1652291&postcount=41), it might be too early to spellcheck. However since I did the work, here is attached my patch anyway :slightly_smiling_face: . Feel free to apply it or discard it and close the issue.

As the development of the book progresses, it is likely that it will not apply cleanly anymore in the future.

Just FIY I used the [typos cli](https://github.com/crate-ci/typos) to generate this patch very quickly: might come in handy in the future!

Cheers

[0001-Round-of-typo-fixes.patch.zip](https://github.com/thorfdbg/rkrm-dos/files/13254539/0001-Round-of-typo-fixes.patch.zip)

**Comment by thorfdbg** [comment]
Patches have been applied, but since the volume grew since last report, a spell checking run is still missing. This will be done as very last step.
