### ISSUE TITLE
Version/kickstart information for function calls 

### ISSUE THREAD

**Issue by jounikor** [thorfdbg/rkrm-dos#5]
Suggest adding two enhancements:
1) Under a subsection of Introduction a table containing kickstart version and matching dos.library versions.
2) For each function or relevant data structure add the version when it was introduced or when something was deprecated.

These might be a bit of work but definitely better the compatibility of programs targeting specific OS versions.

**Comment by thorfdbg** [comment]
Thanks, all the functions and packets should now have version indicators. Please check - thank you.
