### ISSUE TITLE
Document system-startup

### ISSUE THREAD

**Issue by rvalles** [thorfdbg/rkrm-dos#7]
>The decision on the boot process is actually made much earlier, namely by the strap module. At the time the dos.library is starting, the boot volume is already set. The strap module is described in the RKRM devices volume.  However, what I could do is to describe the system-startup. As I'm currently in the second iteration through the book, I would not be able to write it immediately, but please open up a defect report on the git page so I won't forget.

Note it'd also be interesting to document how this changed over time (e.g. kick34 strap definitely knew about nothing about DOS devices).

**Comment by thorfdbg** [comment]
A  very last chapter on System-Startup was added. Note that this does not document strap, whose documentation you find in the RKRM devices manual. If it is incomplete there, it is probably time to redo this volume. (-;
