### ISSUE TITLE
[SUGGESTION] Fitting Start to a Cover Page

### ISSUE THREAD

**Issue by nyteshade** [thorfdbg/rkrm-dos#8]
Made this to make it match my existing PDFs for RKRMs. So happy to have found your work. Throw it away if you don't like it. You'll likely want to change the patterns on the front since those are from the Devices manual. In progress PSD and free font found on MyFonts.com included.

[Cover Page.zip](https://github.com/thorfdbg/rkrm-dos/files/14487014/Cover.Page.zip)
![Thomas_Richter_RKRM_DOS](https://github.com/thorfdbg/rkrm-dos/assets/225558/f6b472e0-c2fa-4243-9e67-dd0f6624016b)

**Comment by thorfdbg** [comment]
Thank you, I made a cover sheet now from scratch, based of course on the same general design, with a couple of variations of the theme.
